services:
  localai:
    image: localai/localai:latest-gpu-nvidia-cuda-12
    container_name: auberge-ai
    volumes:
      - ../data/models:/models
    ports:
      - "8080:8080"

  auberge-app:
    depends_on:
      - localai
