services:
  ollama:
    image: ollama/ollama:latest
    container_name: auberge-ai
    volumes:
      - ollama_storage:/root/.ollama
      - ../data/models:/data/models:ro
      - ./modelfiles:/modelfiles:ro
    ports:
      - "11434:11434"

  auberge-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: auberge-app
    volumes:
      - ../data:/data
      - ../aubergeRP:/app/aubergeRP:ro
      - ../frontend:/app/frontend:ro
      - ../config.yaml:/app/config.yaml:ro
    ports:
      - "${AUBERGE_PORT:-8123}:8000"
    depends_on:
      - ollama

volumes:
  ollama_storage:
