# RTX 4060 (8 GB VRAM)

# qwen3-vl-4b-instruct: 3.4GB
# flux.2-klein-4b: 5.0GB

x-models:
  llm_name: &llm_name qwen3-vl-4b-instruct
  llm_ctx: &llm_ctx 4096
  llm_max_tokens: &llm_max_tokens 1024
  img_name: &img_name flux.2-klein-4b

services:
  localai:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  auberge-app:
    environment:
      AUBERGE_LLM_API_URL: http://localai:8080/v1
      AUBERGE_LLM_MODEL: *llm_name
      AUBERGE_LLM_CONTEXT_WINDOW: *llm_ctx
      AUBERGE_LLM_MAX_TOKENS: *llm_max_tokens
      AUBERGE_IMG_API_URL: http://localai:8080/v1
      AUBERGE_IMG_MODEL: *img_name
