# RTX 5090 (32 GB VRAM)

# qwen3-vl-32b-instruct: 21GB
# flux.2-klein-9b: 10.7GB

x-models:
  llm_name: &llm_name qwen3-vl-32b-instruct
  llm_ctx: &llm_ctx 8192
  llm_max_tokens: &llm_max_tokens 4096
  img_name: &img_name flux.2-klein-9b

services:
  localai:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  auberge-app:
    environment:
      AUBERGE_LLM_API_URL: http://localai:8080/v1
      AUBERGE_LLM_MODEL: *llm_name
      AUBERGE_LLM_CONTEXT_WINDOW: *llm_ctx
      AUBERGE_LLM_MAX_TOKENS: *llm_max_tokens
      AUBERGE_LLM_REPEAT_PENALTY: 1
      AUBERGE_LLM_TEMPERATURE: 1
      AUBERGE_LLM_TOP_K: 64
      AUBERGE_LLM_TOP_P: 0.95
      AUBERGE_IMG_API_URL: http://localai:8080/v1
      AUBERGE_IMG_MODEL: *img_name
